### ISSUE TITLE
ALLOW_ORIGIN settings

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#1]
The ALLOW_ORIGIN settings does not work, if the server uses SSL certificate and someone tries to access the server with the server's ip number. Even though I added the server's ip number to the ALLOWED_ORIGIN settings in the config document.

**Comment by mwambler** [comment]
WEBSOCKET_ALLOWED_ORIGINS is the name of the parameter.  Use the full host name when setting the config (e.g. tekcounsel.net, myurl.com, blah.com)

**Comment by mwambler** [comment]
I am unable to reproduce the issue.  Please re-open if you continue to have the issue.
