### ISSUE TITLE
Broadcast doesn't seem to work

### ISSUE THREAD

**Issue by ABC-ACL** [mwambler/xockets.io#10]
The "broadcast" destination doesn't seem to work.

**Comment by mwambler** [comment]
Would you provide a little more detail on how you are testing the broadcast feature?

**Comment by ABC-ACL** [comment]
sure, I'm doing this, from ssjs:
`websocketBean.sendMessage(from, "broadcast", message);`

**Comment by mwambler** [comment]
Did you get the installed release from openntf, or github? There was a bug with the sendMessage call that I fixed here on github.  I haven't had a chance to post the latest release to openntf.  Download the .zip from this repo, and install 2.0.3 on your system.  The SSJS call should work with this release.

**Comment by ABC-ACL** [comment]
Well, I'm using a version from here: 2.0.3.201604171207
Should I download it again?

**Comment by mwambler** [comment]
That's the right instance.  I'll have a look today and see where it's failing.

**Comment by mwambler** [comment]
This should be fixed with the latest push (still same version).
