### ISSUE TITLE
Sending message to multiple defined users

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#12]
I am trying to send out a single message to two users: I tried 
```
msg.to = ["user1", "user2"]
msg.to = "user1, user2"
msg.to = "user1 user2"
```
Is this possible to do right now, or should I send multiple messages to each user?

**Comment by mwambler** [comment]
Only supports one user at a time

On Monday, May 9, 2016, Csaba Kiss <notifications@github.com> wrote:

> I am trying to send out a single message to two users: I tried
>
> msg.to = ["user1", "user2"]msg.to = "user1, user2"msg.to = "user1 user2"
>
> Is this possible to do right now, or should I send multiple messages to
> each user?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/12>
>


-- 
Mark Ambler

**Comment by mwambler** [comment]
Good idea though... Tag as enhancement

On Monday, May 9, 2016, Mark Ambler <mambler@gmail.com> wrote:

> Only supports one user at a time
>
> On Monday, May 9, 2016, Csaba Kiss <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I am trying to send out a single message to two users: I tried
>>
>> msg.to = ["user1", "user2"]msg.to = "user1, user2"msg.to = "user1 user2"
>>
>> Is this possible to do right now, or should I send multiple messages to
>> each user?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mwambler/xockets.io/issues/12>
>>
>
>
> --
> Mark Ambler
>


-- 
Mark Ambler

**Comment by csakis** [comment]
I don't think I can do that.

**Comment by mwambler** [comment]
Added this feature on latest update.  Version is still 2.0.3 (haven't formally released to openntf).  Please test and let me know.  There is a new attribute in SocketMessage called "targets".  Pass in an array of strings before sending the message and it should route to all of them in one send call.

**Comment by csakis** [comment]
I am gonna give it a try tomorrow. Thanks

**Comment by csakis** [comment]
I get errors:
![image](https://cloud.githubusercontent.com/assets/2583367/15331666/98e126c8-1c1f-11e6-9a42-1c12b7859f0d.png)

**Comment by mwambler** [comment]
Attribute name is targets not target.

On Tuesday, May 17, 2016, Csaba Kiss <notifications@github.com> wrote:

> I get errors:
> [image: image]
> <https://cloud.githubusercontent.com/assets/2583367/15331666/98e126c8-1c1f-11e6-9a42-1c12b7859f0d.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/12#issuecomment-219785968>
>


-- 
Mark Ambler

**Comment by csakis** [comment]
Oops. sorry. It works beautifully. Thanks, Mark. It is very subjective, but it seems to work quicker, too

**Comment by csakis** [comment]
If I remove the msg.to="broadcast" and leave only the msg.targets field, it is definetively much faster getting the message.

**Comment by mwambler** [comment]
It's probably faster if you are sending to a collection of known users or URIs.  There is a short delay for all broadcast based messages as they get persisted and queued first then processed.

**Comment by csakis** [comment]
Indeed, "brodcast" takes ~500 ms, sending to definite users, is virtually instant.

**Comment by mwambler** [comment]
BTW, plugin now supports multiple websocket connections per user based on URI.  Just want you know in case it impacts you in any way see issue #9

**Comment by csakis** [comment]
Wow, wow! That's important. Could you elaborate on that? I would like to
use this feature.
