### ISSUE TITLE
enable debug mode

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#13]
I changed the config doc settings to
WEBSOCKET_DEBUG=true

I get a message in the console to get ready for some serious flood of messages but other than that, I don't see any other changes.
I used to be able to see the PING/PONG traffic from the server  (before version 2.0) to the clients and now there are no extra messages.

**Comment by mwambler** [comment]
Debug mode was more relevant to the prior java_websocket server than netty.  I'm sure there's a similar flag, but the output will not be the same.
