### ISSUE TITLE
Websocket connection times out on IE 11

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#14]
This is a bummer. If I open my application in IE11, after a few minutes of not interacting with the application, the websokcet connection is terminated abnormally.

**Comment by csakis** [comment]
Actually the time out occurs at almost exactly of 37 seconds of inactivity and it's only in IE

**Comment by csakis** [comment]
I solved this problem with a workaround. I detect if the browser is IE, and if it is I send a small websocket message out every 30 seconds. This prevents losing the connection.
```
function isIE() {
    return( /*@cc_on!@*/false || !!document.documentMode);
}

function sendIEStatusMessage {
    ws.sendStatusMessage('IE');
    setTimeout(function() {
        sendStatusMessage();
    }, 30000); 
}

ws { ...
    
    onOpen: function (){
        if (isIE()) {
            sendIEStatusMessage();
        }
    }
}
```

**Comment by mwambler** [comment]
I was able to recreate the issue on my local.  Seems IE11 likes to send Pong messages to the server which currently causes the server to kill the connection due to the unexpected frame type.  I added a fix to accept a Pong message and do nothing in response.  Seems to have fixed the issue.  Please re-test and let me know.

**Comment by csakis** [comment]
I can confirm that IE11 does not terminate connection after installing the
patched server. However, will this change affect the detection of a user
being disconnected in websocket.nsf?

**Comment by mwambler** [comment]
Shouldn't as the close frame is its own structure/format ... I haven't
iterated through all the test scripts though

On Thursday, May 26, 2016, Csaba Kiss <notifications@github.com> wrote:

> I can confirm that IE11 does not terminate connection after installing the
> patched server. However, will this change affect the detection of a user
> being disconnected in websocket.nsf?
>
> On Thu, May 26, 2016 at 7:08 AM, mwambler <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > I was able to recreate the issue on my local. Seems IE11 likes to send
> > Pong messages to the server which currently causes the server to kill the
> > connection due to the unexpected frame type. I added a fix to accept a
> Pong
> > message and do nothing in response. Seems to have fixed the issue. Please
> > re-test and let me know.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mwambler/xockets.io/issues/14#issuecomment-221865455
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/14#issuecomment-221876210>
>


-- 
Mark Ambler
