### ISSUE TITLE
Server side listener remove question

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#15]
My application uses a server side listener. Whenever somebody logs into the application, the page checks if a listener is loaded, and if not a new one will be loaded. Standard stuff.
However, I would like to have an SSJS function that runs every 5 minutes to check if only the listener is loaded and no users are online, if that the case -> remove the script from memory.
Is it possible to call a function from SSJS to unload my server side listener?

**Comment by csakis** [comment]
I have just realized that setTimeout is not implemented in SSJS or in the Rhino version. However, this pieces of code seems to work pretty nicely:
```
var setTimeout,
clearTimeout,
setInterval,
clearInterval;
var setTimeout, clearTimeout, setInterval, clearInterval;

(function () {
    var executor = new java.util.concurrent.Executors.newScheduledThreadPool(1);
    var counter = 1;
    var ids = {};

    setTimeout = function (fn,delay) {
        var id = counter++;
        var runnable = new JavaAdapter(java.lang.Runnable, {run: fn});
        ids[id] = executor.schedule(runnable, delay, 
            java.util.concurrent.TimeUnit.MILLISECONDS);
        return id;
    }

    clearTimeout = function (id) {
        ids[id].cancel(false);
        executor.purge();
        delete ids[id];
    }

    setInterval = function (fn,delay) {
        var id = counter++;
        var runnable = new JavaAdapter(java.lang.Runnable, {run: fn});
        ids[id] = executor.scheduleAtFixedRate(runnable, delay, delay, 
            java.util.concurrent.TimeUnit.MILLISECONDS);
        return id;
    }

    clearInterval = clearTimeout;

})() 
```

I am still trying to figure out how to call the removeSocketListener method from my SSJS listener.
Any tips?

**Comment by mwambler** [comment]
Might be easier to use a scheduled agent nightly to lookup online users and call the below method:

session.SendConsoleCommand("","tell http osgi websocket remove-script...") 

See API help for more info. on the command.  Remember to have it signed by an Id that has rights to send console commands.

**Comment by mwambler** [comment]
Also... just curious, why do you need to remove the script?

**Comment by csakis** [comment]
Now that you made me think about it, I actually do not need to remove the listener from the server. The important thing was the implementation of the setTimeout function (which, by the way, works like a charm). I am running a function recursively and the way I wanted to stop it going all the time was to remove the listener, but now I found another way of getting out of the recursive cycle.

**Comment by csakis** [comment]
I was too hasty, if I use the above code for setting the Timeout function, I lose access to the session object.

**Comment by csakis** [comment]
For future reference, here is my solution. First here is the problem, the code above is very excellent for using setTimeout or setInterval functions, but it uses `ScheduledThreadPoolExecutor` and once that executes, i cannot get access to the underlying Domino database, for example the  session.getDatabase() function silently fails. 
However, I can still send websocket messages at specific intervals. So instead of executing the database specific functions inside the `setInterval(dbFunction, 30000`), I send a simple websocket message to the server, and then the server executes the `dbFucntion()` upon receiving the sent websocket message:` OnMessage() {dbFucntion()} `
