### ISSUE TITLE
socket message created on the server is not delivered to the listener

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#16]
I might be doing something wrong, but when I am trying to send a message out using a server side listener, the server never receives the message.
I tried to send the message to "broadcast", "/*", "rhino/app.nsf/ssjslistener", "websocket/*" 
```
var msg = websocketClient.createMessage();
msg.setTo("broadcast"); 
msg.setText("");
msg.getData().put("status","ping"); 
websocketClient.sendMsg(msg);
```
The OnMessage() function never fires in my listener for these types of messages. 
What am I doing wrong?

**Comment by mwambler** [comment]
Double check function name.  onMessage not OnMessage

On Friday, June 3, 2016, Csaba Kiss <notifications@github.com> wrote:

> I might be doing something wrong, but when I am trying to send a message
> out using a server side listener, the server never receives the message.
> I tried to send the message to "broadcast", "/*",
> "rhino/app.nsf/ssjslistener", "websocket/*"
>
> var msg = websocketClient.createMessage();
> msg.setTo("broadcast");
> msg.setText("");
> msg.getData().put("status","ping");
> websocketClient.sendMsg(msg);
>
> The OnMessage() function never fires in my listener for these types of
> messages.
> What am I doing wrong?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/16>, or mute the thread
> <https://github.com/notifications/unsubscribe/AEI46doF20cNKNH1_Ko1L0N7LvlgHnCrks5qIFrQgaJpZM4Ittbl>
> .
>


-- 
Mark Ambler

**Comment by csakis** [comment]
That's a good point, but that's not the issue, if I send the same message from a client, the listener gets it and executes the appropriate function, but if I try to send the message using the listener, it never arrives to the listener. If I use 'broadcast", I can see the message arriving to the clients, but npt tp the listener.

**Comment by mwambler** [comment]
There is code to prevent the listener from responding to itself.

On Friday, June 3, 2016, Csaba Kiss <notifications@github.com> wrote:

> That's a good point, but that's not the issue, if I send the same message
> from a client, the listener gets it and executes the appropriate function,
> but if I try to send the message using the listener, it never arrives to
> the listener. If I use 'broadcast", I can see the message arriving to the
> clients, but npt tp the listener.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/16#issuecomment-223653413>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEI46anCeQRUWdcRrzHYbQ9DifbAlS3hks5qIG9vgaJpZM4Ittbl>
> .
>


-- 
Mark Ambler

**Comment by csakis** [comment]
That explains it. I am working around it.
