### ISSUE TITLE
msg.targets problem

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#17]
I don't know if it's a feature or a bug. I use the msg.targets property to send my messages to the users and to the server side listener. I have an array of 
`msg.targets = ["rhino/app.nsf/listener.ssjs", "/app.nsf/5645C7FF9D464B6085EB22A2CCFE0F13EAE5EBA9"]`
It works if onle one user is logged in, however, as soon as the second user logs in, they will not get the message.
This part `/app.nsf/5645C7FF9D464B6085EB22A2CCFE0F13EAE5EBA9` is the URI, which every user gets when they log in. I tried to use * at the end of the URI, it did not help.

1. Can the msg.targets use URI for sending messages?
2. Do I need to specifiy each recipient?
3. Can I use wildcards?

**Comment by csakis** [comment]
I confirmed this on another server. If I use a URI to send the message to, then only one user 
(usually the one that logged in first time) will get websocket messages form the server.
If I create an array with the user names, then all users will receive the messgae. It seems that a msg.target works only if it's only for single recipient.

**Comment by csakis** [comment]
It seesm that issue is much deeper than I thought originally. At the moment, only one user receives messages no matter if I use msg.targets or msg.to.
I went back and checked older builds of the server. It works until the May 16th version, as soon as I install the May 25th version, when you introduced the msg.targets property, the server breaks.

**Comment by mwambler** [comment]
If you are using multiple targets make sure the to field is not set.  Below
script works fine for me (note I have the "to" attribute commented out)


```javascript

var msg = new Object();
//msg.to=listUsers.value;
msg.targets=[listUsers.value,"rhino/chat.nsf/ssjs.websocket.listener"];
msg.text = txtMessage.value;
msg.from = txtFrom.value;
var json = JSON.stringify(msg);
chatClient.send(json);
txtMessage.value="";
txtMessage.focus();

```



On Tue, Jun 14, 2016 at 1:57 PM, Csaba Kiss <notifications@github.com>
wrote:

> It seesm that issue is much deeper than I thought originally. At the
> moment, only one user receives messages no matter if I use msg.targets or
> msg.to.
> I went back and checked older builds of the server. It works until the May
> 16th version, as soon as I install the May 25th version, when you
> introduced the msg.targets property, the server breaks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/17#issuecomment-225963266>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEI46d35wmYSo8NEWk9-iWcRW_YdHhfRks5qLut6gaJpZM4I0rFs>
> .
>



-- 
Mark Ambler

**Comment by csakis** [comment]
We commented out the msg.to field. That did not solve the problem. Can you check if your listUsers.value contain any URI type address? If you use well defined users in the listUser.value array, then that's not a good test. You need to test with a multiple recipient value such as a URI. 
If I have my users listed as an array, then each user will receive their messages, but users on the same  URI, if there are multiple users logged in, only one of them will receive the message.
Furthermore, The messgae coming from the server uses msg.to instead of msg.targets. Can this be the problem

**Comment by csakis** [comment]
By the way, as I mentioned before, it's not speicific to the targets attribute, if I try to use 
`msg.to = "app.nsf/5645C7FF9D464B6085EB22A2CCFE0F13EAE5EBA9*"`
only one of the users at that URI will receive the message

**Comment by mwambler** [comment]
I see it... bug was introduced when I moved to multiple websockets open per
user.

On Tue, Jun 14, 2016 at 4:09 PM, Csaba Kiss <notifications@github.com>
wrote:

> By the way, as I mentioned before, it's not speicific to the targets
> attribute, if I try to use
> msg.to = "app.nsf/5645C7FF9D464B6085EB22A2CCFE0F13EAE5EBA9*"
> only one of the users at that URI will receive the message
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/17#issuecomment-226000651>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEI46eFqQY4VUoZGEN5EA2nEX0EutmICks5qLwphgaJpZM4I0rFs>
> .
>



-- 
Mark Ambler

**Comment by csakis** [comment]
Cool, as soon as you have a fix, I will test it. Thanks, Mark.

**Comment by mwambler** [comment]
Just posted the build 2.0.6.  Please download from github and let me know if it works for you.  Note, I haven't fully tested this release.  I'll cycle it through this weekend...

**Comment by csakis** [comment]
BOOYAH!!!
It works now, Thanks Mark.
