### ISSUE TITLE
Websocket installation without enabling secure connection

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#18]
I have been trying to install the latest websocket plugin on a dev server using simple http and unsecured ws connection.
I get lots of errors that I have not seen before. Here is my config doc:

```
#start websocket settings
WEBSOCKET_PORT=8080
WEBSOCKET_PROXY_BACKEND_HOST=127.0.0.1
WEBSOCKET_PROXY_BACKEND_PORT=80
WEBSOCKET_REDIRECT_PORTS=80
#username used for server-side operations (e.g. agent signer)
WEBSOCKET_USER=websocket
WEBSOCKET_PASSWORD=****
#debug/test settingg
WEBSOCKET_DEBUG=false
WEBSOCKET_TEST_MODE=false
WEBSOCKET_MAX_MSG_SIZE=15977336
#security settings
#WEBSOCKET_FILTER=com.tc.websocket.filtrestart serverer,com.tc.websocket.filter.AllowedCharsFilter
WEBSOCKET_ALLOW_ANONYMOUS=false
WEBSOCKET_THREAD_COUNT=1
WEBSOCKET_EVENT_LOOP_THREADS=2
WEBSOCKET_MAX_CONNECTIONS=8000
WEBSOCKET_ALLOWED_ORIGINS=127.0.0.1, 128.165.134.208, cktest.lanl.gov
#network encryption settings
WEBSOCKET_ENCRYPT=false
#WEBSOCKET_KEYSTORE_PATH=C:/domino/websocket.jks
#WEBSOCKET_KEY_PASSWORD=*****
#WEBSOCKET_KEYSTORE_PASSWORD=*****
#WEBSOCKET_KEYSTORE_TYPE=JKS
WEBSOCKET_COMPRESSION_ENABLED=true
WEBSOCKET_SEND_BUFFER=16384
WEBSOCKET_RECEIVE_BUFFER=16384

```

See attached log and error files:
[console.log.txt](https://github.com/mwambler/xockets.io/files/357874/console.log.txt)
[error-log-0.xml.txt](https://github.com/mwambler/xockets.io/files/357873/error-log-0.xml.txt)
[startup.log.txt](https://github.com/mwambler/xockets.io/files/357872/startup.log.txt)
[trace-log-0.xml.txt](https://github.com/mwambler/xockets.io/files/357871/trace-log-0.xml.txt)

**Comment by csakis** [comment]
Update 1:
I removed everything from the config document and the server started up nicely, albeit with lot of warnings.
```
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: Opening trusted session to gain access to the config document.
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: Config session is CN=csaba/O=home
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: Loading websocket configuration from notes.ini
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: ****WARNING: WEBSOCKET_USER and WEBSOCKET_PASSWORD are not setup.  xockets.io will run under a trusted session.****
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: Send buffer is 8192 bytes
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: Receive buffer is 8192 bytes
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: ****WARNING: All origins are allowed. Not recommended****
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: Loading 2 event loop thread(s).
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: Loading 1 other background thread(s).
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: Purge interval is 900 seconds.
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: Compression disabled
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: Maximum connections 200
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: ****WARNING: Websocket connections not encrypted.****
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: ****WARNING: Anonymous access is allowed.****
[20E8:0002-1CE8] 07/11/2016 04:12:24 PM  HTTP JVM: xockets.io service: No websocket filter registered.
[20E8:0002-1CE8] 07/11/2016 04:12:25 PM  HTTP JVM: xockets.io service: xockets.io ready and listening on 8889 running version 2.0.6
[20E8:0002-1CE8] 07/11/2016 04:12:25 PM  XSP Command Manager initialized
[20E8:0002-1CE8] 07/11/2016 04:12:27 PM  HTTP Server: Started
```
I will investigate further

**Comment by csakis** [comment]
**Update 2:**
It works now. I had to use the full user name in my config document such as
`websocket websocket/home`
with the short name it did not work.
I still get one error message 
![image](https://cloud.githubusercontent.com/assets/2583367/16750610/d9062a6c-4787-11e6-8fa7-3f0fc261c106.png)
but it does not seem to effect the server.

Can you please clarify, if these security settings are correct and if I need to add the websocket user anywhere else:
![image](https://cloud.githubusercontent.com/assets/2583367/16750643/1037ba3c-4788-11e6-9973-6f648df65431.png)

**Comment by mwambler** [comment]
Looks like you have it covered.  Just make sure the id you are using has
appropriate ACL settings to websocket.nsf and any other .nsf it will
interact with.

On Monday, July 11, 2016, Csaba Kiss <notifications@github.com> wrote:

> *Update 2:*
> It works now. I had to use the full user name in my config document such as
> websocket websocket/home
> with the short name it did not work.
> I still get one error message
> [image: image]
> <https://cloud.githubusercontent.com/assets/2583367/16750610/d9062a6c-4787-11e6-8fa7-3f0fc261c106.png>
> but it does not seem to effect the server.
>
> Can you please clarify, if these security settings are correct and if I
> need to add the websocket user anywhere else:
> [image: image]
> <https://cloud.githubusercontent.com/assets/2583367/16750643/1037ba3c-4788-11e6-9973-6f648df65431.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/18#issuecomment-231899945>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEI46RjGUFXlAjNQmv4QrvgYB3MeN2_eks5qUteqgaJpZM4JJsIe>
> .
>


-- 
Mark Ambler

**Comment by csakis** [comment]
Just to make sure. 

What ACL does the websocket user need for websocket.nsf (I use: Manager with delete) and for websocketupdate.nsf?

**Comment by mwambler** [comment]
Editor with deletion should do... Designer or higher on target nsf for
rhino / ssjs scripts

On Monday, July 11, 2016, Csaba Kiss <notifications@github.com> wrote:

> Just to make sure.
>
> What ACL does the websocket user need for websocket.nsf (I use: Manager
> with delete) and for websocketupdate.nsf?
>
> > On Jul 11, 2016, at 6:10 PM, mwambler <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Looks like you have it covered. Just make sure the id you are using has
> > appropriate ACL settings to websocket.nsf and any other .nsf it will
> > interact with.
> >
> > On Monday, July 11, 2016, Csaba Kiss <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > *Update 2:*
> > > It works now. I had to use the full user name in my config document
> such as
> > > websocket websocket/home
> > > with the short name it did not work.
> > > I still get one error message
> > > [image: image]
> > > <
> https://cloud.githubusercontent.com/assets/2583367/16750610/d9062a6c-4787-11e6-8fa7-3f0fc261c106.png
> >
> > > but it does not seem to effect the server.
> > >
> > > Can you please clarify, if these security settings are correct and if I
> > > need to add the websocket user anywhere else:
> > > [image: image]
> > > <
> https://cloud.githubusercontent.com/assets/2583367/16750643/1037ba3c-4788-11e6-9973-6f648df65431.png
> >
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/mwambler/xockets.io/issues/18#issuecomment-231899945>,
> > > or mute the thread
> > > <
> https://github.com/notifications/unsubscribe/AEI46RjGUFXlAjNQmv4QrvgYB3MeN2_eks5qUteqgaJpZM4JJsIe
> >
> > > .
> > >
> >
> >
> > --
> > Mark Ambler
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub <
> https://github.com/mwambler/xockets.io/issues/18#issuecomment-231902356>,
> or mute the thread <
> https://github.com/notifications/unsubscribe/ACdrR-YrZp3tqsojywIN5diU1XWVTtBeks5qUtthgaJpZM4JJsIe
> >.
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/18#issuecomment-231902728>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEI46WUGqZMV2cxqjvYsO7ZnF55u8x7mks5qUtwCgaJpZM4JJsIe>
> .
>


-- 
Mark Ambler
