### ISSUE TITLE
test/framework

### ISSUE THREAD

**Issue by mrmiggles** [mwambler/xockets.io#2]
Hi Mark,

Not really an issue but more of what's inside the test/framework. I just didn't know how else to contact you. When I attempt to export the jar I get several missing plug-in errors, all which seem to be from com.ibm.xsp/domino/notes, etc. Did you just extract those jars from domino framework and drop them into the project or do you have another method?

	Missing required plug-in com.ibm.domino.osgi.core_0.0.0.
	Missing required plug-in com.ibm.commons_0.0.0.
	Missing required plug-in com.ibm.pvc.servlet_0.0.0.
	Missing required plug-in com.ibm.xsp.extsn_0.0.0.
	Missing required plug-in com.ibm.xsp.core_0.0.0.
	Missing required plug-in com.ibm.xsp.designer_0.0.0.
	Missing required plug-in com.ibm.xsp.dojo_0.0.0.
	Missing required plug-in com.ibm.xsp.domino_0.0.0.
	Missing required plug-in com.ibm.notes.java.api_1.0.0.
	Missing required plug-in com.ibm.designer.runtime_0.0.0.
	Missing required plug-in com.ibm.wink_0.0.0.
	Missing required plug-in com.ibm.domino.services_0.0.0.
	Missing required plug-in com.ibm.domino.das_0.0.0.

I apologize for posting this as an issue.

Thank you,

Miguel Gallegos

**Comment by mwambler** [comment]
Hi Miguel,
You will need to setup eclipse dev environment and add all the domino OSGi
plugins to your workspace.  There is an SDK plugin you can add to
facilitate setup.  You will want a local install of domino as well.  There
might still be a tutorial on how to setup on openntf.

1). Install eclipse RAP / RCP
2). Install Domino locally (you could reference the same plugins from the
client)
3) Install Xpages SDK RCP


https://openntf.org/main.nsf/project.xsp?r=project/XPages%20SDK%20for%20Eclipse%20RCP/releases/0C60A1BFF5F40FD586257D8D005AA593

Let me know if you continue to run into problems.  I'll put a blog post
together on setup if needed.

On Monday, March 14, 2016, mrmiggles <notifications@github.com> wrote:

> Hi Mark,
>
> Not really an issue but more of what's inside the test/framework. I just
> didn't know how else to contact you. When I attempt to export the jar I get
> several missing plug-in errors, all which seem to be from
> com.ibm.xsp/domino/notes, etc. Did you just extract those jars from domino
> framework and drop them into the project or do you have another method?
>
> Missing required plug-in com.ibm.domino.osgi.core_0.0.0.
> Missing required plug-in com.ibm.commons_0.0.0.
> Missing required plug-in com.ibm.pvc.servlet_0.0.0.
> Missing required plug-in com.ibm.xsp.extsn_0.0.0.
> Missing required plug-in com.ibm.xsp.core_0.0.0.
> Missing required plug-in com.ibm.xsp.designer_0.0.0.
> Missing required plug-in com.ibm.xsp.dojo_0.0.0.
> Missing required plug-in com.ibm.xsp.domino_0.0.0.
> Missing required plug-in com.ibm.notes.java.api_1.0.0.
> Missing required plug-in com.ibm.designer.runtime_0.0.0.
> Missing required plug-in com.ibm.wink_0.0.0.
> Missing required plug-in com.ibm.domino.services_0.0.0.
> Missing required plug-in com.ibm.domino.das_0.0.0.
>
> I apologize for posting this as an issue.
>
> Thank you,
>
> Miguel Gallegos
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/2>.
>


-- 
Mark Ambler

**Comment by mrmiggles** [comment]
Thanks Mark. I setup my eclipse dev environment and imported all the OSGI plugins to my workspace. I installed domino locally and referenced all the domino plugins I was missing. I'm still working out some kinks but I think I'm almost there. I'm still missing the lotus.domino.database/session plugins and it appears they are there within the ibm.notes.java.api but I'm still getting some errors. Might have imported it incorrectly. I'm almost there. I'll close this after I figure it out just so I don't keep bugging if I can't figure it out.

**Comment by mwambler** [comment]
Did you get the IDE / project working?

On Monday, March 14, 2016, mrmiggles <notifications@github.com> wrote:

> Thanks Mark. I setup my eclipse dev environment and imported all the OSGI
> plugins to my workspace. I installed domino locally and referenced all the
> domino plugins I was missing. I'm still working out some kinks but I think
> I'm almost there. I'm still missing the lotus.domino.database/session
> plugins and it appears they are there within the ibm.notes.java.api but I'm
> still getting some errors. Might have imported it incorrectly. I'm almost
> there. I'll close this after I figure it out just so I don't keep bugging
> if I can't figure it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/2#issuecomment-196545621>.
>


-- 
Mark Ambler

**Comment by mrmiggles** [comment]
I couldn't get the open ntf plugin working. I think maybe because I am
using Eclipse Mars. I'll downgrade and give Luna a try tonight...although I
don't expect that's the problem. Thank you for the follow up.


Miguel

**Comment by mrmiggles** [comment]
Hi Mark,

So I got the environment set up and the importing of the plugin is all imported with no errors or warnings. I'm currently learning OSGI bundling how to export the plugins so it exactly matches your com.tc.websocket.updatesite folder upon export. I think your work is probably done on this part unless you have some advice for exporting these bundles otherwise I think we can consider this a closed "issue". 

You've been a great help. My hopes for this are understanding and maintaining it alone. 

Thanks again!

Miguel Gallegos

**Comment by mwambler** [comment]
Hi Miguel,
Good to hear you got it working.
