### ISSUE TITLE
webauth_verbose logging

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#26]
If I enable verbose web authentication logging, my console is flooded with these messages:
![image](https://cloud.githubusercontent.com/assets/2583367/19078077/2c7963aa-8a0c-11e6-9baa-af16c25b86de.png)

Is this normal?

**Comment by mwambler** [comment]
websocket is the name of your userId for websocket?  If yes, then does make sense as the server/plugin opens and closes sessions all the time.

**Comment by csakis** [comment]
Yes, the websocket user is websocket and everything works fine,
