### ISSUE TITLE
websocket broken after 2.0.2 update

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#3]
I tried to update my dev server to the latest and greatest. However, When I am trying to establish a websocket connection, I get this error:
![image](https://cloud.githubusercontent.com/assets/2583367/13969486/d28d0426-f048-11e5-8d30-1c1f92f64d5a.png)

**Comment by mwambler** [comment]
Double check your configuration settings.  If you upgraded to FP5 make sure the java.policy file is setup correctly as well.

**Comment by mwambler** [comment]
seems this is a duplicate of, or related to, issue #4.
