### ISSUE TITLE
Can I access the actual database name from a listener/observer?

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#36]
I am trying not to hard-code the name of the nsf into my listeners like this
`var CURRENT_DB = session.getDatabase("","chat.nsf");`

I tried using `session.getCurrentDatabase();` but that returns null.
The problem is that if someone changes the name of the nsf, then the application breaks. It would be nice to use a dynamic name, instead of a hard-coded one. Is that possible right now?

**Comment by mwambler** [comment]
Try:

var CURRENT_DB = session.getDatabase("", **script.dbPath()**);

**Comment by csakis** [comment]
Thanks, Mark. 
Beautiful. Now I can generalize my app easily.
