### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by AntonJonasson** [mwambler/xockets.io#38]
Hi Mark, I've been using your websocket for xpages and encountered a strange error. Using the skeleton from your chat application, when the observer.ssjs file got to large (around 700 lines), the compiler threw an error. Looking at the error log file, i saw that somewhere my code got injected with some strange characters, Üÿùÿ N. This would appear at the same line in the code, but would move whenever I added a ; at an earlier point in the file. Commenting out the line affected solved the problem. The characters to not appear to have been injected on my end, it seems to happen in the compilation process. Dividing the code up into several smaller files fixed the issue. Do you have any idea what this could be?

**Comment by AntonJonasson** [comment]
The version I am using is 9.0.1 FP8.
Here is the file printed in the error log. The error i mentioned is visible on line 547.
[tmp8643435378334358532.txt](https://github.com/mwambler/xockets.io/files/1197237/tmp8643435378334358532.txt)

**Comment by mwambler** [comment]
I believe it has to do with the way Domino stores script design elements. Once you reach a certain length in a script lib it will create another file reference behind the scenes. You took the right approach in splitting the script into smaller units.
