### ISSUE TITLE
secure port settings

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#4]
The blog post for xocket 2.0.2 shows port 8443:
![image](https://cloud.githubusercontent.com/assets/2583367/13970474/8da7b51c-f04e-11e5-8bf4-bda6509e58b8.png)

That's an unusual port, is this correct?
http://markwambler.blogspot.com/2016/03/xocketsio-202.html

**Comment by mwambler** [comment]
You need to alter the Domino port settings so they don't conflict with the WEBSOCKET_PORT.  If you want Domino and websocket running off the same port, set the WEBSOCKET_PORT=443.

**Comment by csakis** [comment]
My Domino port settings:
![image](https://cloud.githubusercontent.com/assets/2583367/13987181/f134bb02-f0cb-11e5-880f-0cce4911aaac.png)

My config settings:
![image](https://cloud.githubusercontent.com/assets/2583367/13987205/14b963fc-f0cc-11e5-8ab0-58c601a2c52c.png)

Error in console

> [12AC:0013-1B74] 03/23/2016 07:47:19 AM  HTTP Web Server: IBM Notes Exception - File does not exist [/websocket/chat.nsf/20B7EFF85DAA81A4B6F82312F4B778FABB6B1250] CN=Csaba Kiss/O=csaba

Error in browser:
![image](https://cloud.githubusercontent.com/assets/2583367/13987252/516936a6-f0cc-11e5-8630-a1d70494d84a.png)

Errors in log:

> 2016-03-23T07:46:44.030-06:00 SEVERE   com.tc.websocket.server.DominoWebSocketServer 
2016-03-23T07:47:19.585-06:00 SEVERE   com.tc.websocket.embeded.clients.RhinoClient 
2016-03-23T07:47:19.594-06:00 SEVERE   com.tc.websocket.embeded.clients.RhinoClient 

I updated my java.policy with these lines:
`grant {
permission java.security.AllPermission;
};`

And the server is updated to FP5. I am stumped.

**Comment by mwambler** [comment]
Change the domino port for SSL to 8443.  Full bounce of domino server

On Wednesday, March 23, 2016, Csaba Kiss <notifications@github.com> wrote:

> My Domino port settings:
> [image: image]
> <https://cloud.githubusercontent.com/assets/2583367/13987181/f134bb02-f0cb-11e5-880f-0cce4911aaac.png>
>
> My config settings:
> [image: image]
> <https://cloud.githubusercontent.com/assets/2583367/13987205/14b963fc-f0cc-11e5-8ab0-58c601a2c52c.png>
>
> Error in console
>
> [12AC:0013-1B74] 03/23/2016 07:47:19 AM HTTP Web Server: IBM Notes
> Exception - File does not exist
> [/websocket/chat.nsf/20B7EFF85DAA81A4B6F82312F4B778FABB6B1250] CN=Csaba
> Kiss/O=csaba
>
> Error in browser:
> [image: image]
> <https://cloud.githubusercontent.com/assets/2583367/13987252/516936a6-f0cc-11e5-8630-a1d70494d84a.png>
>
> Errors in log:
>
> 2016-03-23T07:46:44.030-06:00 SEVERE
> com.tc.websocket.server.DominoWebSocketServer
> 2016-03-23T07:47:19.585-06:00 SEVERE
> com.tc.websocket.embeded.clients.RhinoClient
> 2016-03-23T07:47:19.594-06:00 SEVERE
> com.tc.websocket.embeded.clients.RhinoClient
>
> I updated my java.policy with these lines:
> grant {
> permission java.security.AllPermission;
> };
>
> And the server is updated to FP5. I am stumped.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/4#issuecomment-200354376>
>


-- 
Mark Ambler

**Comment by csakis** [comment]
I did that:

I receive a general SSL error:
This site cannot provide a secure connection

error-log-0.xml 
`2016-03-23T10:21:00.518-06:00 SEVERE   com.tc.websocket.server.handler.ProxyFrontendHandler `

**Comment by csakis** [comment]
This issue has been closed, but unfortunately, it's not solved.

**Comment by mwambler** [comment]
Re-opened the issue.  Would you post more of the log / exception?

**Comment by csakis** [comment]
Here is my trace-log and the config file:
[trace-log-7[xml].txt](https://github.com/mwambler/xockets.io/files/187891/trace-log-7.xml.txt)
[configdoc.txt](https://github.com/mwambler/xockets.io/files/187893/configdoc.txt)

and a screenshot of the server port settings
![image](https://cloud.githubusercontent.com/assets/2583367/14018087/5e6f05ea-f191-11e5-9e13-05f52878bade.png)

**Comment by mwambler** [comment]
Try re-installing the java cryptography extension from IBM (two jars).  I think you may have had this problem before 

java.security.InvalidKeyException: Illegal key size or default parameters.

**Comment by csakis** [comment]
You're right. I use a 4k key. Let me try to reinstall 2.0.2 and the jars and I will come back to you

**Comment by csakis** [comment]
It works!!! Thanks, Mark. I am gonna do a stress test on the server and post the results on my blog.
