### ISSUE TITLE
URI are case sensitive

### ISSUE THREAD

**Issue by smart717** [mwambler/xockets.io#41]
HI!
I dont know if it's a bug but if 2 users on the same server access to:

user 1: http://192.168.0.8/ChAt.nsf
user 2: http://192.168.0.8/chat.nsf

if user 2 send a message to /chat.nsf* , user 1 does not receive the message

Broadcast messages works.

Thank you!

**Comment by mwambler** [comment]
I guess a "case" could be made for or against :). I suggest making sure the client(s) generate the websocket URI consistently since it is the path of least resistance. FYI, be sure to pull the latest release from github as the last version published on openntf has some memory leaks

**Comment by smart717** [comment]
Thank you! i'm working with latest release from github.

In my scenario the error could occur because in some cases the URI is communicated orally.
I solved it anyway using the "getCustomWebSocketUrl" function so that it always uses the database path and NOT the request path.
