### ISSUE TITLE
console command issues

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#5]
I am having problems with the following console commands:

`tell http osgi websocket show-scripts`

`tell http osgi websocket remove-script  app.nsf/script`

I am running two websocket applications on my server. They both use server side listeners, yet the two commands above do not show any script running on the server.
If I issue
`tell http osgi websocket show-users`

I can see that the listeners are loaded on the server

**Comment by mwambler** [comment]
show-scripts is not referenced anymore.  I must have removed while refactoring.  I'll add it to the next release.

**Comment by mwambler** [comment]
xockets.2.0.3 up.  The show-scripts and reload-scripts commands are now working... please re-test.

**Comment by csakis** [comment]
I tried show-script and remove-script. They don't seem to do anything.

**Comment by mwambler** [comment]
What version of the plugin is listed on your update site?  Also, post
screen capture of what you are sending

On Monday, April 11, 2016, Csaba Kiss <notifications@github.com> wrote:

> I tried show-script and remove-script. They don't seem to do anything.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/5#issuecomment-208473335>
>


-- 
Mark Ambler

**Comment by csakis** [comment]
Update site:
![image](https://cloud.githubusercontent.com/assets/2583367/14437140/125ed446-ffdd-11e5-8a23-a5749f004e89.png)

Console commands:
![image](https://cloud.githubusercontent.com/assets/2583367/14437173/315d43f0-ffdd-11e5-8bd4-c418e8ba7e9f.png)

websocket users:
![image](https://cloud.githubusercontent.com/assets/2583367/14437192/50800b0a-ffdd-11e5-8c3f-97917cf0c7d6.png)

**Comment by mwambler** [comment]
Based on your screen capture... looks like you removed the script, then tried to show-scripts, which printed nothing to the console.  I did notice that the rhino client was still connected after removing the script. Adding a call to disconnect the client upon script removal.

**Comment by csakis** [comment]
Since I don't get any feedback from the console command, it's diffcult to
know if anything is happening.

**Comment by mwambler** [comment]
OK.. I'll add some feed back (e.g. "No registered scripts found")

**Comment by mwambler** [comment]
OK.. just pushed up build to disconnect client, and remove the scripts associated.  Please re-try the command line operations.

**Comment by csakis** [comment]
Yup, they work now.

**Comment by csakis** [comment]
When I try to remove scripts from running on the server using the console commands
`tell http osgi websocket remove-script app.nsf/script`
the server gives me a feedbakc that the script has been disconnected, however, in my application the 
`websocketBean.containsSocketListener("/app.nsf/ssjs.listener")`
still come back as true. I have to restart the http task to clear the listener from memory.

The reload-scripts command works very well, though

**Comment by mwambler** [comment]
Fix for this has been pushed up.  Make sure you add a leading slash to the listener when removing from the command line (e.g. tell http osgi websocket remove-script /chat.nsf/ssjs.listener)
