### ISSUE TITLE
Stress testing xocket.io

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#7]
I modified your chat.nsf and added a button to it with this code executing, if I click the button:

```
var text = "Hippopotamus quit futile a oyster special...."; //long random text
var INTERVAL = 25; //time in milliseconds.
var textArray = text.split(" ");
var arrayLength = textArray.length;
var i =0;
delayMessage(i);
function delayMessage (i) {
	if (i>10000) return;
 	chatText = i + "-> ";
 	for (var j=0; j<10; j++) {
 			chatText +=textArray[Math.floor(Math.random()*arrayLength)] + " ";
 		}
 	var msg = new Object();
 	msg.to="/chat.nsf*";
 	msg.text = chatText;
 	msg.date = new Date().getTime();
 	msg.from = txtFrom.value;
 	var json = JSON.stringify(msg);
 	chatClient.send(json);
 	i +=1;
 	setTimeout(function(){delayMessage(i)}, INTERVAL);
 }
```

The code sends out 10,000 random 10-word messages. I can control how often send the messages out by changing the INTERVAL constant.  
If I go under 10 ms, which means a hundred messages sent in a second, I get these errors:
![image](https://cloud.githubusercontent.com/assets/2583367/14234743/fa1c61c2-f9a7-11e5-83d1-cfc4651344fc.png)

Probably, we will never reach this message "density", nevertheless, I thought you should know.

**Comment by mwambler** [comment]
If you use a single word or phrase (instead of random) at the same
interval, does it still fail have a problem?

On Sunday, April 3, 2016, Csaba Kiss <notifications@github.com> wrote:

> I modified your chat.nsf and added a button to it with this code
> executing, if I click the button:
>
> var text = "Hippopotamus quit futile a oyster special...."; //long random text
> var INTERVAL = 25; //time in milliseconds.
> var textArray = text.split(" ");
> var arrayLength = textArray.length;
> var i =0;
> delayMessage(i);
> function delayMessage (i) {
>     if (i>10000) return;
>     chatText = i + "-> ";
>     for (var j=0; j<10; j++) {
>             chatText +=textArray[Math.floor(Math.random()*arrayLength)] + " ";
>         }
>     var msg = new Object();
>     msg.to="/chat.nsf*";
>     msg.text = chatText;
>     msg.date = new Date().getTime();
>     msg.from = txtFrom.value;
>     var json = JSON.stringify(msg);
>     chatClient.send(json);
>     i +=1;
>     setTimeout(function(){delayMessage(i)}, INTERVAL);
>  }
>
> The code sends out 10,000 random 10-word messages. I can control how often
> send the messages out by changing the INTERVAL constant.
>
> If I go under 10 ms, which means a hundred messages sent in a second, I
> get these errors:
> [image: image]
> <https://cloud.githubusercontent.com/assets/2583367/14234743/fa1c61c2-f9a7-11e5-83d1-cfc4651344fc.png>
>
> Probably, we will never reach this message "density", nevertheless, I
> thought you should know.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/7>
>


-- 
Mark Ambler

**Comment by csakis** [comment]
You are on the right track.
If I used the 
`msg.text = "I'm a random message from the button.";`
The server could handle sending/receiving the messages better and breaks later. It could almost manage 2-5 ms. It breaks after around 7-8000 messages.
It passed 10 ms twice.

**Comment by mwambler** [comment]
Is the exception different this time?

On Sunday, April 3, 2016, Csaba Kiss <notifications@github.com> wrote:

> You are on the right track.
> If I used the
> msg.text = "I'm a random message from the button.";
> The server could handle sending/receiving the messages better and breaks
> later. It could almost manage 2-5 ms. It breaks after around 7-8000
> messages.
> It passed 10 ms twice.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/7#issuecomment-205062303>
>


-- 
Mark Ambler

**Comment by csakis** [comment]
It’s the same  JSON utility error.

On April 3, 2016 at 4:11:24 PM, mwambler (notifications@github.com) wrote:

Is the exception different this time?

On Sunday, April 3, 2016, Csaba Kiss <notifications@github.com> wrote:

> You are on the right track.
> If I used the
> msg.text = "I'm a random message from the button.";
> The server could handle sending/receiving the messages better and breaks
> later. It could almost manage 2-5 ms. It breaks after around 7-8000
> messages.
> It passed 10 ms twice.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/7#issuecomment-205062303>
>


--
Mark Ambler

**Comment by mwambler** [comment]
Please post the whole stack trace.  Also, are you profiling the browser.
Connection closing abruptly might be on browser side.  I've seen this error
when I terminate my unit tests early.

On Sunday, April 3, 2016, Csaba Kiss <notifications@github.com> wrote:

> It’s the same  JSON utility error.
>
> On April 3, 2016 at 4:11:24 PM, mwambler (notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>) wrote:
>
> Is the exception different this time?
>
> On Sunday, April 3, 2016, Csaba Kiss <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > You are on the right track.
> > If I used the
> > msg.text = "I'm a random message from the button.";
> > The server could handle sending/receiving the messages better and breaks
> > later. It could almost manage 2-5 ms. It breaks after around 7-8000
> > messages.
> > It passed 10 ms twice.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mwambler/xockets.io/issues/7#issuecomment-205062303>
> >
>
>
> --
> Mark Ambler
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/7#issuecomment-205070143>
>


-- 
Mark Ambler

**Comment by csakis** [comment]
Io did not close the browser window, I left it alone. The error comes in way after all the messages have been sent but the server is trying to catch up with them. here are the traces.


[error-log-0[xml].txt](https://github.com/mwambler/xockets.io/files/201666/error-log-0.xml.txt)
[trace-log-0[xml].txt](https://github.com/mwambler/xockets.io/files/201667/trace-log-0.xml.txt)

[console[log].txt](https://github.com/mwambler/xockets.io/files/201668/console.log.txt)

**Comment by mwambler** [comment]
Based on the stack trace, looks as though the JSON sent by the client was invalid.  The server didn't crash, just threw a parsing exception (no OOM exceptions).  How long did you run the test?  If your XPage/Domino session times out, the application will remove the user and close the connection.   Note, I used your script on my local machine with a few alterations  1)  I removed the reference to the ssjs listener, 2) I added a check for count to clear the chathistory after every 1k messages.


var text = "Hippopotamus quit futile a oyster special...."; //long random text
var INTERVAL = 25; //time in milliseconds.
var textArray = text.split(" ");
var arrayLength = textArray.length;
var i =0;
delayMessage(i);
function delayMessage (i) {
    if (i>10000) return;
    
    if(i % 1000===0){
    	chatHistory.innerHTML="";
    }
    
    chatText = i + "-> ";
    for (var j=0; j<10; j++) {
            chatText +=textArray[Math.floor(Math.random()*arrayLength)] + " ";
            
        }
    console.log(chatText);
    var msg = new Object();
    msg.to="/chat.nsf*";
    msg.text = chatText;
    msg.date = new Date().getTime();
    msg.from = txtFrom.value;
    var json = JSON.stringify(msg);
    chatClient.send(json);
    i +=1;
    setTimeout(function(){delayMessage(i)}, INTERVAL);
 }

**Comment by csakis** [comment]
Here are some updates.
Today I ran the test on another setup. In ths case the client and the server are on two differnet computers. The server has the latest xocket 2.0.2 with TLS  enabled. I also removed the client side javascript that enters the text into the chatHistory, otherwise the script becomes very slow.
I changed the random text with something else. I ran the test with 5 ms intervals.
I need to keep track of the messages on the server so I have a simple server side listernet that saves the messages into a document:
`
var db = session.getDatabase("","chat.nsf");
var doc = db.createDocument(); 
doc.replaceItemValue("Form","chat"); 
doc.replaceItemValue("Author", socketMessage.getFrom());
doc.replaceItemValue("chat", socketMessage.getText());
doc.save();
`
First time, after 6818 messages I get the JSONUtils error.
Second time, all messages have been sent but browser stopped receiving messages from the server at this message:
`
{date:1459864983466
from:"CN=Csaba Kiss/O=csaba"
text:"9013-> old Improve hastily either. are drift household. furniture had. On "
to:"/chat.nsf*}
` 
and I get the JSON.util error again in the console.log.

Third time: Script stoppped sending out messages at 6718:
`
{date:1459865354661
from:"CN=Csaba Kiss/O=csaba"
text:"6718-> had oh things Known nature edward. impression denied.Admiration my round "
to:"/chat.nsf*}`

It seems that the error happens at random times. The JSON message has nothing funky about it, as far as I can see.

You are right that the server itself does not crash, however, the client disconnects, and the user needs to refresh the browser.

If I change the interval to 10 ms (ran the test 3 times), then everything is fine. So it must be some kind of buffering or queueing issue. 

I even opened three browser windows and sent out 10000 messages concurrently from each window. The server coull handle a 20-ms interval.

**Comment by mwambler** [comment]
Next build will log invalid JSON.  I'll push it up tonight along with other
fixes.

On Tuesday, April 5, 2016, Csaba Kiss <notifications@github.com> wrote:

> Here are some updates.
> Today I ran the test on another setup. In ths case the client and the
> server are on two differnet computers. The server has the latest xocket
> 2.0.2 with TLS enabled. I also removed the client side javascript that
> enters the text into the chatHistory, otherwise the script becomes very
> slow.
> I changed the random text with something else. I ran the test with 5 ms
> intervals.
> I need to keep track of the messages on the server so I have a simple
> server side listernet that saves the messages into a document:
>
> var db = session.getDatabase("","chat.nsf");
> var doc = db.createDocument();
> doc.replaceItemValue("Form","chat");
> doc.replaceItemValue("Author", socketMessage.getFrom());
> doc.replaceItemValue("chat", socketMessage.getText());
> doc.save();
>
> First time, after 6818 messages I get the JSONUtils error.
> Second time, all messages have been sent but browser stopped receiving
> messages from the server at this message:
>
> {date:1459864983466
> from:"CN=Csaba Kiss/O=csaba"
> text:"9013-> old Improve hastily either. are drift household. furniture
> had. On "
> to:"/chat.nsf*}
>
> and I get the JSON.util error again in the console.log.
>
> Third time: Script stoppped sending out messages at 6718:
>
> {date:1459865354661
> from:"CN=Csaba Kiss/O=csaba"
> text:"6718-> had oh things Known nature edward. impression
> denied.Admiration my round "
> to:"/chat.nsf*}
>
> It seems that the error happens at random times. The JSON message has
> nothing funky about it, as far as I can see.
>
> You are right that the server itself does not crash, however, the client
> disconnects, and the user needs to refresh the browser.
>
> If I change the interval to 10 ms (ran the test 3 times), then everything
> is fine. So it must be some kind of buffering or queueing issue.
>
> I even opened three browser windows and sent out 10000 messages
> concurrently from each window. The server coull handle a 20-ms interval.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/7#issuecomment-205837501>
>


-- 
Mark Ambler

**Comment by mwambler** [comment]
xockets.2.0.3 up.  Added additional logging for any json parsing exceptions.  Please re-test with this build and see what json is failing in the log(s).

**Comment by csakis** [comment]
I re-tested it. Here are the error logs.

[error-log-0[xml].txt](https://github.com/mwambler/xockets.io/files/213581/error-log-0.xml.txt)
[trace-log-0-[xml].txt](https://github.com/mwambler/xockets.io/files/213582/trace-log-0-.xml.txt)

**Comment by mwambler** [comment]
Would you check log.nsf to see if the errant JSON is there?  I have a logging statement in JSONUtils to try and grab it.

**Comment by mwambler** [comment]
if you set the following notes.ini parameter.  It should dump everything into log.nsf:  HTTP_OSGI_ENABLE_CONSOLE_LOGGING = 1

**Comment by mwambler** [comment]
Ran this many times over.  I can't re
![javascript-parsing-error](https://cloud.githubusercontent.com/assets/4339945/14468118/51f77ac0-00ac-11e6-8f86-14f7c99d3182.PNG)
produce the problem.

**Comment by csakis** [comment]
I, looks like that the messages are partial fragment JSON messages like these:
```
{"to":"/chat.nsf*","text":"1024-> rapturous his spirit but believi
{"to":"/chat.nsf*","text":"345-> vanity oh set. vanity Shyness add b

```

I don't know which part of message generation fails. I keep the browser window in the foreground.

**Comment by csakis** [comment]
You might need to decrease the time to 5 ms in the Timeout.
I am not sure how relevant this test is, though.
