### ISSUE TITLE
User is null. closing connection...

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#8]
Reproducing error:
Make sure websocket does not allow anonymous.
Load chat.nsf -> Get Connected message.
Reload page -> Disconnected. User is null....

Downgrading to 2.0.3 fixes the issue.

**Comment by mwambler** [comment]
Have you tested with anonymous set to true (does it continue to work)?  Also, this makes me think your session is timing out, closing your websocket connection mid-message..  Check the session timeout in xsp.properties and increase to 30 minutes.

**Comment by csakis** [comment]
It happens only with the version with the added console commands. I have not tested with anonymous enabled. 
When I refresh the page, the error occurs, I don't need to wait for a session time out.

**Comment by mwambler** [comment]
I ran it... No issues with anonymous set to false on my local server

On Saturday, April 16, 2016, Csaba Kiss <notifications@github.com> wrote:

> It happens only with the version with the added console commands. I have
> not tested with anonymous enabled.
> When I refresh the page, the error occurs, I don't need to wait for a
> session time out.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/8#issuecomment-210921062>
>


-- 
Mark Ambler

**Comment by csakis** [comment]
Weird. Both my work and home server behave the same way.

**Comment by mwambler** [comment]
What is the session timeout in xsp.properties?  I've had it set to 1 before to test the SessionListeners, so I still think it might be that.  Please check and let me know.

**Comment by csakis** [comment]
I checked your chat.nsf. The xsp.timeout was set at 1 minute. I set it to 30 minutes, then I removed the settings completely. 
It does not make any difference. I load the page first and it is fine. As soon as I hit the Reload button, I get disconnected.  I need to close all browser windows and log in again.
The ACL for anonymous is No Access in the chat.nsf.

**Comment by csakis** [comment]
As soon as I check the 2.0.3 branch out (April 6) and install that on the sever, the issue goes away.

**Comment by mwambler** [comment]
I was able to repeat the User is null problem.  I found the issue.  In the last push I inadvertently flagged the user to be removed when the xpage is refreshed.  That bug is not in the April 6 code.  I'm glad I waited to release it. I'll have a build up today for you to re-test.

**Comment by mwambler** [comment]
New build up, please pull and test.

**Comment by csakis** [comment]
I had to do my taxes first. Now it's back to normal and the console commands work, too.
