### ISSUE TITLE
Multiple websockets per user/sessionID

### ISSUE THREAD

**Issue by ABC-ACL** [mwambler/xockets.io#9]
When a user has multiple tabs/windows open on the same xpage (or nsf), only one of them receives the messages.

**Comment by mwambler** [comment]
Currently this feature is not supported as the server only supports one websocket connection per user session.  I will tag this as an enhancement for future reference.

**Comment by mwambler** [comment]
Latest update (still version 2.0.3 as I have yet to upload to openntf) now supports this feature.  Multiple open websocket connections per user based on URI.  Please download from here, test, and let me know.

**Comment by csakis** [comment]
Oh, I did not see this ticket. I will try it.

**Comment by csakis** [comment]
This enhancement behaves weirdly, not as expected. Let me try to explain.

1. I log in with one application (1 user, 1 server side listener).
2. Evertyhing is fine, I see two users in the users by URI view, websocket connection is established
3. I open an incognito window and login with the same user a different application that also has  a server side listener component.
4. Websocket connection is established correctly, I can see another listener is activated, however, the normal user with the previous uri is replaced with the new user.
5. I refresh any of the browser windows and I see a new "normal" user in the Users by URI, but the URI is wrong, it's only "/".

So, something is not perfect

**Comment by mwambler** [comment]
You aren't testing it correctly.  Use the same browser / session you created.  Open the other application in a new tab off the same server.  You should see two URIs listed, and a show-users command will render 2 websocket connections for that user's session/Id.

**Comment by csakis** [comment]
You are correct, if the same user is in the same session, then it works correctly.

**Comment by csakis** [comment]
Thanks, this is a great feature.

**Comment by mwambler** [comment]
thank @ABC-ACL he's the one that asked for it... Although... still waiting for him to confirm if it's working for him or not.

**Comment by ABC-ACL** [comment]
Hi Mark,

Works great! Thanks!

**Comment by mwambler** [comment]
Thanks for testing it ... going to push up a build to Openntf
